### ISSUE TITLE
Selection Square Data Resets

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#10]
1) When inputting custom NW, SE coordinates into the boxes, if the user then selects "USE" below it, it will reset all of the coordinates.

2) Can we get it to where these custom coordinates are saved from previous session?

**Comment by drchuck59** [comment]
This has been corrected in release 1.1.0

**Comment by KSanders7070** [comment]
1-Not fixed
2-That was fixed however, the moment I select "Create Square & Center on ARTCC", it reverts them all back.

I understand why this is happening but the issue is that the square that your program automatically makes for our ARTCC (ZLC) is too small and we like to expand it out to this:
    Northwest corner - N053.35.40.585 W127.30.00.000
    Southeast Corner - N031.24.44.995 W096.09.59.991
