### ISSUE TITLE
Navigraph Data Use

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#11]
It is not clear how to use the Navigraph data.

What NG file do we use?

How do we select to pull data from that rather than the FAA data?

What limits are there?

etc...

**Comment by drchuck59** [comment]
Add a subfolder for NaviGraph inside your SCT-Builder data folder.  (ALL data for SCT builder goes in one data folder; SCT Builder will search subfolders to find your resource data.)  From NaviGraph Updater, add the SCT location and use "PMDG (all compatible products)".  Note that SCT Builder will ignore NaviGraph data if the AIRAC does not match the FAA AIRAC in the resource folder.
