### ISSUE TITLE
Need Refresh After DATA Download

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#14]
(release 1.1.0) After the data is done downloading from the FAA, the Data Cycle in Use area still says "No active cycle data!". Restarting the program fixes this issue and it is recognized upon start. (was not an issue with previous releases)

**Comment by drchuck59** [comment]
Actually, it was present in pre-releases.  I forgot to fix it!  Will do for v 1.1.1

**Comment by drchuck59** [comment]
Corrected in v1.1.1
