### ISSUE TITLE
Runway Centerlines off sometimes

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#15]
There seems to be issues with the negative mag variation and the Runway Centerlines at ZLC when the RWY is near a 360 heading.

KIDA airport will be used for this example.

03  21  27  207 N043.30.09.064 W112.05.06.793 N043.31.19.074 W112.03.51.564; IDA-IDAHO FALLS RGNL
17  35  171 -9  N043.31.21.326 W112.03.41.759 N043.30.41.364 W112.03.43.572; IDA-IDAHO FALLS RGNL

That -9 should be 350 or 351.

**Comment by drchuck59** [comment]
Corrected in v 1.1.1
