### ISSUE TITLE
[REQUEST] SID/STAR Name Format

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#16]
With your prior releases, you exported all of the SID/STARs into a single file called "ZLC_SID.txt"... now you give each of them their own txt file and I apprieate all of that however, I wrote a batch file for your previous releases that would take all of the files that your program created and export them into a single .SCT2 file in the appropriate order.  Could I get you to change your format for naming the SID/STARs (and future regions) as follows:

ZLC_SID_RUGGD.txt

I can then rewrite my batch file like you see attached and it will then write them in alphabetical order for me.
![Capture](https://user-images.githubusercontent.com/63331106/84968010-7b3ecf00-b0e3-11ea-8e76-ecbc75b8b600.JPG)

**Comment by KSanders7070** [comment]
Also,

Where are the ARTCC_LOW.txt, ARTCC_HIGH.txt, AirwayLow.txt, and AirwayHigh.txt files that were there before?

**Comment by KSanders7070** [comment]
Disregard. I see what you are doing. It wouldn't help to rename the file.

**Comment by drchuck59** [comment]
Summary (full) SID STAR output will come with v1.2; I have to get NaviGraph interfacing with the FAA data correctly (so that ALT and SPEED can be drawn), as well as make some tweaks to the Labels and Symbols code.  Then I'll re-enable the combined output (which is too large to evaluate in testing).

**Comment by KSanders7070** [comment]
Awesome! Thanks!
