### ISSUE TITLE
NaviGraph Data Confusion

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#19]
Assume we have never used NaviGraph...

When accessing the NaviGraph Data Manager, what data would we download from NG to use with your builder?

What file do we bring to the FAA data folder?

etc...

For example, we chose the X-Plane 11 download from the Data Manager.
Are we bringing over the CIFP folder into the FAA folder that we created? Do we only bring over the .dat files? or do we bring over the earth_awy.dat file for example?

If you decided to give us instructions for this, may I suggest an update to the Wiki for this builder to reflect those instructions?

**Comment by KSanders7070** [comment]
I didn't fully read the last issue response from you. Sorry. Still think that the Wiki could be used as an "instruction manual" and could use an update though.

**Comment by drchuck59** [comment]
No problem - I don't know how to use a Wiki, and I don't have time to learn, so I won't be going there.
Use the PMDG style of download in NaviGraph Data Manager and set the target folder as your SCTBuilder data folder.

**Comment by KSanders7070** [comment]
I meant YOUR wiki. A step by step there would be very nice.

https://github.com/drchuck59/SCTBuilder/wiki/SCT-Builder-for-Virtual-Radar-Client
