### ISSUE TITLE
UE after Center on ARTCC to APT

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#20]
Seems like there is an Unhandled Exception error when the user first runs the Builder via a "Center on ARTCC" option, then opens the program later on and this time selects "Center on APT".

**Comment by drchuck59** [comment]
I haven't been able to reproduce that error.  Can you add screenshots of the steps you used to produce the error?

**Comment by drchuck59** [comment]
Yes, this error was related to the APT UE.  Fixed in v 1.2.1.  Thanks!
