### ISSUE TITLE
Selecting Center on APT = UE

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#21]
Not sure if it has anything do with the previously reported issue "UE after Center on ARTCC to APT": https://github.com/drchuck59/SCTBuilder/issues/20

After a remove of your Builder program and a fresh install:

When selected ZLC as the ARTCC and Main APT as SLC and selecting Center on APT, we get an Unhandled Exception.

**Comment by drchuck59** [comment]
Fixed in v1.2.1 - thanks!
