### ISSUE TITLE
Deselect AIRPORTS doesn't auto Deselect RWYs

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#23]
Extremely low priority (opinion)

Recreate:

SELECT: AIRPORTS

SELECT: RUNWAYS

DESELECT: AIRPORTS

RUNWAYS stays selected (checked) but grays out... this causes a notification during restart of the program that is a little weird.

**Comment by drchuck59** [comment]
Fixed - thanks!
