### ISSUE TITLE
Unhandled Exceptions

### ISSUE THREAD

**Issue by Nikolai558** [drchuck59/SCTBuilder#24]
Not sure what difference / changes there was between v 1.1.1 and v 1.1.2 but there are some new "unhandled exceptions" happening" Follow the steps below to recreate.

- Fresh install V1.1.2
- Select Folder Data: "Desktop\ZLC_FE_SCT_BUILDER\Data"
- Select Folder Output:  "Desktop\ZLC_FE_SCT_BUILDER\Output"
- Click "Update AIRAC"

Once AIRAC download complete:
- Select "ZLC" 
- Select "SLC"
- Click "Center on APT Button" (CAUSES UNHANDLED EXCEPTION) (click "continue")
- Click "Center on ARTCC"
- Select all options (Airport, Runway, Fixes, etc.)
- Click Black arrow

Once complete:
- Click "Generate VRC Files" 
(Program starts and seems to get to "SIDS" then causes UNHANDLED EXCEPTION)

I have tried multiple fresh installs, one where I do not cause the first Unhandled Exception, however, I can not get the VRC Files to complete in any instance when SIDS or STARS are selected.

**Comment by drchuck59** [comment]
Yes, this was why I had to completely rebuild SIDS and STARS.  Not to mention, a rebuild was needed to be ready for MetroPlex SID/STAR formats (included in v1.2.1). Thanks for the bug reports!  I try to button test but clearly cannot find all of them.
