### ISSUE TITLE
VOR'S UE (V 1.2.1)

### ISSUE THREAD

**Issue by Nikolai558** [drchuck59/SCTBuilder#27]
Another Unhandled Exception Occurs, this time when it reaches the VOR's after clicking "Generate VRC Files"

- Start V1.2.1
- ARCC: ZLC, Main Apt: SLC, Create Square & Center on ARTCC
- Select ALL except "Oceanic"
- Black arrow
- Once completed, "Generate VRC files"
- Unhandled Exception occurs. I have found out that it hits VORS and gives you a UE

![image](https://user-images.githubusercontent.com/38259407/86522200-9ade3300-be17-11ea-9050-24003200ffb2.png)

Everything else seems to be working nicely. SIDS and STARS look way better. They are leaving off VOR's but I'm assuming this is because I did not select VOR's in order to get the SIDS and STARS without hitting the UE.

**Comment by drchuck59** [comment]
I found this as well.  It was due to a change in SID file structure (the airport identifier abbreviation changed from AA to NA).  I corrected that in v1.2.2 - try building one SID that has a VOR in it.  Try v1.2.2 and close this issue if the problem does not occur.

**Comment by Nikolai558** [comment]
Dude, you are amazing! --Fixed
