### ISSUE TITLE
ZLC (KSLC) MAG VAR Wrong

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#28]
Running 1.3.0

CREATE SQUARE & CENTER ON ARTCC (ZLC)
CENTER ON APT (SLC)

MAG VAR displays as:
5.00

That means it would be 5W but KSLC airport is 11E so it should display:
-11.0

![ZLC SLC MAG VAR](https://user-images.githubusercontent.com/63331106/86543245-cb42d180-beea-11ea-9c89-1acce46e3e1e.JPG)

**Comment by drchuck59** [comment]
Fixed in v1.3.1.  Thanks!
