### ISSUE TITLE
Insufficient Settings to Resume

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#29]
After uninstalling <1.3.1 via the setup.exe "uninstall"... clearing %temp% data, re-index of my computer, and everything... restarting the computer, downloading and installing 1.3.1... upon launch, this is the first thing that pops up.
![First start](https://user-images.githubusercontent.com/63331106/86628923-9bea9e00-bf98-11ea-8bec-f093600f43b4.JPG)

**Comment by drchuck59** [comment]
Included in another issue
