### ISSUE TITLE
Uninstall Doesn't remove all data

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#30]
As reference HERE: https://github.com/drchuck59/SCTBuilder/issues/29

I uninstalled everything and cleared the %temp% folder and even restarted and when I launched the new downloaded 1.3.1, it remembered my last input [INFO] data.

This may be an issue if we are trying to troubleshoot any issues and may even be contributing to that other issue: https://github.com/drchuck59/SCTBuilder/issues/29

**Comment by drchuck59** [comment]
The uninstall issue may be related to a bad installation parameter I discovered in v1.3.2.  Hopefully fixed in v1.3.3.

**Comment by KSanders7070** [comment]
Seems to be fixed but the release version according to GitHub is 1.3.2
