### ISSUE TITLE
ARTCC Boundary (almost complete)

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#31]
ZLC ARTCC Boundary is really close but doesn't finish. Obviously this is easy to fix manually so I wouldn't consider it a high priority fix but thought you should know about it.

EDIT: It also seems this data is being placed in the LOW & HIGH BOUNDARIES section rather than ARTCC BOUNDARIES
![ZLC ARTCC Boundary](https://user-images.githubusercontent.com/63331106/86631615-5b8d1f00-bf9c-11ea-8d44-b0317c6c713b.JPG)

**Comment by KSanders7070** [comment]
EDIT: It also seems this data is being placed in the LOW & HIGH BOUNDARIES section rather than ARTCC BOUNDARIES

**Comment by drchuck59** [comment]
Closure line added (close issue if successful).  As for LOW and HIGH, those are governed by the FAA text data.  FEs can move them wherever their DATM prefers.

**Comment by KSanders7070** [comment]
Great job! This looks to be exactly on point now.
