### ISSUE TITLE
Use the %temp%?

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#32]
After the download of FAA cycle data, the .zip is still left in the users Downloads folder.

May I suggest making use of the %temp% directory for this and then when the download is complete and transferred to the users selected "DATA" directory, your program could delete the .zip from the %temp% directory.

To make things easier to code, maybe the first thing the program should do when the user selects "UPDATE AIRAC" is:

*Does this directory exist?  %temp%\SCTBuilder_temp_data\

**If true: download FAA data there

**If False: Create Directory and then download FAA data there.

*At the end of the process: DELETE data inside %temp%\SCTBuilder_temp_data\

![TEMP Folder usage](https://user-images.githubusercontent.com/63331106/86632220-19181200-bf9d-11ea-8281-fa68dde37d18.JPG)

**Comment by drchuck59** [comment]
Excellent idea!  Done in 1.3.3  Also done for the XML preferences file to keep it out of prying eyes. LOL
