### ISSUE TITLE
UE On Second Run

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#35]
This happened on 1.3.0 as well but I forgot to report it. Sorry.

For the most part, everything works when you install 1.3.1 and you are able to run it just fine. Upon restart of the program, you are met with an UE.

I have tried uninstalling it, doing an advanced Disk Cleanup, restarted computer, reinstalled 1.3.1 and it still is met with UE on launch.

SOLUTION:
-Run as Admin.

However, it doesn't remember any of the previously used data when you run as admin.
[UE Details.txt](https://github.com/drchuck59/SCTBuilder/files/4881089/UE.Details.txt)

**Comment by drchuck59** [comment]
I need to alter the default resource folder.  It's looking in the application folder (which requires admin access).  I'll fix that.

**Comment by KSanders7070** [comment]
This seems to have been fixed with latest release. I will allow you to opt to close it.
