### ISSUE TITLE
No Airway Lines 

### ISSUE THREAD

**Issue by Nikolai558** [drchuck59/SCTBuilder#38]
The airway breaks issue was solved, however, the fix seemed to have cause another issue. The airway lines are no longer being drawn, just the labels. See picture below of one example.

![image](https://user-images.githubusercontent.com/38259407/86696816-0b798100-bfcb-11ea-86fc-d2a2b5f1faa1.png)

**Comment by KSanders7070** [comment]
FOUND THE ISSUE:

Lets take the first airway line "T259" for example...

T259                       N037.59.12.539 W119.14.15.560 N037.59.12.539 W119.14.15.560; BNAKI WEXIM

The first coordination should be BNAKI and it very might be... then the second coordinate should be WEXIM but its not... the second set of coordinates is actually the same as the first (BNAKI)... You are drawing lines with only a single point of reference for each line to be drawn.

**Comment by drchuck59** [comment]
Break fix corrected in v 1.3.3 - thank you!
