### ISSUE TITLE
New VATSIM Logo

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#39]
Not a priority, just thought you would like to update your About Page.. https://www.vatsim.net/news/big-day-vatsim
![PPcBlgO](https://user-images.githubusercontent.com/63331106/88340168-54d70980-cd09-11ea-9a6f-56fd1b4a9bba.jpg)

**Comment by drchuck59** [comment]
Tried it.  Soesn't fit and look good at the same time.
