### ISSUE TITLE
Airac cycle date calculation wrong - Custom User date/time format

### ISSUE THREAD

**Issue by Nikolai558** [drchuck59/SCTBuilder#4]
When the user changes their computer date/time format from the default, you code does something funky when calculating the Airac cycle dates. Once you hit "Airac Update" and select an Airac to download, it will through an unhanded exception because the website you download the data from doesn't exist because the Airac cycle dates are wrong. This can be fixed by either handling the exception it throws, or verifying that the users date/time that you pull matches the format you are requesting in your code. I am more than happy to assist you to fix this issue.

**Comment by drchuck59** [comment]
This will be fixed in next revision.  Needs to have the "culturevariant" option enabled.
