### ISSUE TITLE
Canada Aiways

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#40]
It appears there are some airways that are start in USA airspace and go up to canada that stop being drawn at the Canadian boarder at the Computer Navigation Fix/Mileage Breakdown (CNF) and then go down directly to S199.00.00.000.

Then there are some that don't...

Take ZLC for example:
-J478 starts at GGW and goes NW to CFCKK and is suppose to continue to YQL but instead, stops at CFCKK and goes down to S199.00.00.000.

-Same with J517 from GEG to EDGES then to BZXIV to YXC. But it stops at BZXIV and goes straight down to S199.00.00.000

-But... J599 right next to J517 crosses the boarder at a CNF but doesn't go down to S199.00.00.000

![Capture](https://user-images.githubusercontent.com/63331106/88601610-127e3700-d03f-11ea-8a1a-524db83003aa.PNG)
![2Capture](https://user-images.githubusercontent.com/63331106/88601611-13af6400-d03f-11ea-93f4-684a1c58a106.PNG)

**Comment by drchuck59** [comment]
Currently, only FAA data is utilized, and the FAA text files do not include cross-border data (although this is available in non-readable format from FAA).  Will investigate use of NaviGraph data to supplement results.

**Comment by drchuck59** [comment]
Error shown above has been fixed.  However, it will be some time before I start using NaviGraph data for non-US functions.
