### ISSUE TITLE
[REQ] Closed Airports

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#41]
Requesting Closed airports to be included into the sector file data.

Reason: You can sometimes still provide approaches/services form closed airports/runways.

Reference: https://github.com/drchuck59/SCTBuilder/issues/34

**Comment by drchuck59** [comment]
I will add an option in Preferences.  Be forewarned, this will increase both time and size of the files!

**Comment by drchuck59** [comment]
After review of FAA data and discussion amongst FEs, this enhancement will not be implemented.  Primarily thhe FAA data does not maintain updated data on the closed airfields - e.g., the RWYs are not corrected.  On reflection of the purpose of this software, this enhancement would enable FEs to create non-standard, not-current AIRAC displays.
