### ISSUE TITLE
Airway Fix Errors

### ISSUE THREAD

**Issue by BeaconSlash** [drchuck59/SCTBuilder#42]
Hi there,

Was just referred to your tool by a NASR_2_SCT developer, Mr. Sanders.  Trying to compile some data now with your tool, and I wanted to report a couple errors.  Before that though, loving your tool so far.  I really appreciate the ability to trim the data set with that box.  It conforms well to how ERAM limits its GeoMap data set.  Thank you!

When inputting selection square data, I put in North as N045.25.00.000 and it auto-corrects to N045.24.60.000 Not sure if that affects functionality at all.  I put in N45.25.01.000 to ensure coverage and that value remained unchanged.

When generating airways, there are a handful that shoot off far away.  I can compile more if desired, but a couple of examples of data generated are:

V320                       N045.37.50.338 W084.39.50.790 N062.57.03.711 W155.36.40.946; PLN MCG
V320                       N062.57.03.711 W155.36.40.946 N045.21.07.465 W084.55.27.182; MCG LORIW
V320                       N045.21.07.465 W084.55.27.182 N045.11.20.356 W085.04.30.401; LORIW IROTO

The actual airway only goes PLN to LORIW, no MCG. In the preview panel, it does show correctly. Just the output file seems to contain MCG.

Different though is V456 which generates (just showing last two of many other legs here):

V456                       N044.35.49.255 W093.37.16.295 N044.49.31.266 W093.26.33.677; WULEP FCM
V456                       N044.49.31.266 W093.26.33.677 N059.34.34.356 W154.24.36.947; FCM NOSKY

NOSKY is not on the airway, and FCM appears to be the terminus.  Here the preview panel does show FCM and NOSKY.

I am on AIRAC 2101

Selection Square is (margins all 0):

N N045.25.01.000
W W096.00.00.000
S N038.50.00.000
E W082.47.59.000

Thanks for the tool and the work!

**Comment by drchuck59** [comment]
Thank you!  Indeed this was a bug in the math and has been corrected!
