### ISSUE TITLE
Airway Generation Issues

### ISSUE THREAD

**Issue by BeaconSlash** [drchuck59/SCTBuilder#44]
First, big improvement after your last fix.  Thank you for your work.

I generated a set of airway data (among other information) from AIRAC 2102

Selection Square:
North N045.25.00.000
West W096.00.00.000
South N038.50.00.000
East W082.48.00.000

All margin values set to zero (BTW what is the effect of the margins value?)

Output to VRC file and viewed some points far outside selection square.  Specifically:

**V320                       N045.37.50.338 W084.39.50.790 N062.57.03.711 W155.36.40.946; PLN MCG
V320                       N062.57.03.711 W155.36.40.946 N045.21.07.465 W084.55.27.182; MCG LORIW**
V320                       N045.21.07.465 W084.55.27.182 N045.11.20.356 W085.04.30.401; LORIW IROTO
V320                       N045.11.20.356 W085.04.30.401 N045.01.50.316 W085.13.13.542; IROTO ADENO
V320                       N045.01.50.316 W085.13.13.542 N044.52.40.725 W085.21.35.151; ADENO TIDDU
V320                       N044.52.40.725 W085.21.35.151 N044.49.54.173 W085.24.06.378; TIDDU SKIPR
V320                       N044.49.54.173 W085.24.06.378 N044.40.04.495 W085.33.00.038; SKIPR TVC
V320                       N044.40.04.495 W085.33.00.038 N044.12.37.645 W085.11.24.833; TVC ZOLOX
V320                       N044.12.37.645 W085.11.24.833 N043.52.19.371 W084.55.41.190; ZOLOX ICADA
V320                       N043.52.19.371 W084.55.41.190 N043.37.22.172 W084.44.14.160; ICADA MOP
V320                       N043.37.22.172 W084.44.14.160 N043.31.53.928 W084.04.38.284; MOP MBS
**V320                       N043.31.53.928 W084.04.38.284 N060.28.46.035 W149.03.29.894; MBS MURYY**

See MCG and MURYY

V456                       N042.36.40.053 W094.17.41.334 N042.43.34.307 W094.16.05.369; FOD HOXIV
V456                       N042.43.34.307 W094.16.05.369 N042.50.10.529 W094.14.33.193; HOXIV SHELB
V456                       N042.50.10.529 W094.14.33.193 N043.14.12.196 W094.08.54.814; SHELB BANCO
V456                       N043.14.12.196 W094.08.54.814 N043.40.36.575 W094.02.37.681; BANCO BLEND
V456                       N043.40.36.575 W094.02.37.681 N044.13.11.661 W093.54.44.473; BLEND MKT
V456                       N044.13.11.661 W093.54.44.473 N044.24.34.393 W093.45.59.216; MKT ZANNA
V456                       N044.24.34.393 W093.45.59.216 N044.35.49.255 W093.37.16.295; ZANNA WULEP
V456                       N044.35.49.255 W093.37.16.295 N044.49.31.266 W093.26.33.677; WULEP FCM
**V456                       N044.49.31.266 W093.26.33.677 N059.34.34.356 W154.24.36.947; FCM NOSKY**

See NOSKY

V462                       N042.36.40.053 W094.17.41.334 N042.49.33.628 W094.47.31.309; FOD SIMJI
V462                       N042.49.33.628 W094.47.31.309 N042.55.55.966 W095.02.27.437; SIMJI NELIC
V462                       N042.55.55.966 W095.02.27.437 N043.15.15.244 W095.48.33.382; NELIC NEWRN
V462                       N043.15.15.244 W095.48.33.382 N043.24.30.547 W096.11.04.563; NEWRN CATID
**V462                       N043.24.30.547 W096.11.04.563 N058.59.39.236 W158.33.07.976; CATID DLG**

See DLG

**V508                       N039.08.43.595 W096.40.07.434 N061.19.53.980 W157.23.01.860; MHK YOCUK
V508                       N061.19.53.980 W157.23.01.860 N039.15.51.073 W095.56.10.193; YOCUK ZOYFY**
V508                       N039.15.51.073 W095.56.10.193 N039.13.48.094 W095.49.53.747; ZOYFY KENEC
V508                       N039.13.48.094 W095.49.53.747 N039.08.13.478 W095.32.57.017; KENEC TOP
V508                       N039.08.13.478 W095.32.57.017 N039.00.24.719 W095.08.08.947; TOP RUGBB

See YOCUK

Jet airways appear to have generated correctly.  No lines appear to be inappropriately shooting off outside the selection square.

This tool is great!

**Comment by drchuck59** [comment]
The FAA does not segment airways by ARTCC with a fix, allowing controllers to flex who has control over boundaries.  If any portion of the next segment is within your square, the program will extend the airway past the square so that center controllers have the next waypoint in the segment.  This output appears to be working correctly; it is supposed to add that segment rather than risk leaving a segment missing.

**Comment by BeaconSlash** [comment]
I don't mind the fact a given segment goes beyond the selection square if it's part of the airway.  I totally understand that and it makes sense.

The fixes bolded/mentioned above though are both not part of the airways and far outside the selection box boundary.  It doesn't make sense that they're included in the airway output at all.
