### ISSUE TITLE
Generate VRC Files Grey Out

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#5]
After running the parser, the ‘Generate VRC Files’ button stays grayed out. This use to automatically become available in previous versions. We have found that if you reselect your primary airport, it will show up.

**Comment by drchuck59** [comment]
Yes - I also discovered same.  What was the last thing you clicked before reselecting the airport?

**Comment by KSanders7070** [comment]
The black arrow to start the parsing.

**Comment by KSanders7070** [comment]
I didn't mean to close this out.

**Comment by KSanders7070** [comment]
This only happens if SID/STAR are selected.

**Comment by drchuck59** [comment]
The software is working as designed.   The issue no longer appears in version 1.1.0.
