### ISSUE TITLE
Airways Inaccurate

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#6]
Your airways seem to start in the right area but then tend to drift off with random points and other points are skipped over.

An example of v328 is attached

[v328_example.txt](https://github.com/drchuck59/SCTBuilder/files/4536761/v328_example.txt)

**Comment by drchuck59** [comment]
Thanks!  I'll look into that!  The entire Airways parser needs to be reconfigured anyway.

**Comment by Nikolai558** [comment]
Hello Chuck,
I have found something to note. Right now your Airways are "incomplete." Look at V328 for example. Your parser gives out 11 fixes, the correct number of fixes in this airway is 23.

In SCToutput.cs roughly line 477; "If (CurAwy == PrevAwy)" If you change this specific line to "If (CurAwy != PrevAwy)" it will give you all the missing fixes with some additional ones at the start and ending.

This means in the same file, roughly line 500; "PrevAwy = CurAwy" is in the wrong place. I am currently looking at where it should be. I will keep you updated via discord or in here.

**Comment by drchuck59** [comment]
Changed in v1.1.0  - please retest

**Comment by drchuck59** [comment]
Corrected in v 1.1.1 - enter new Issue if found in error
