### ISSUE TITLE
Airway Breaks

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#7]
The FAA seems to be decommissioning a lot of airways but they don't seem to always take the entire airways offline.

Example: V200 starts at ENI and ends at FMG. It then picks back up at BVL and ends at RLG.
Your parser draws a line between FMG and BVL still.

I consulted with Casey from MyFSim.com and he says that the FAA puts some "X" somewhere in their data to represent a break in the airway.

IDK much more about it though.

**Comment by KSanders7070** [comment]
Found it... in the AWY.txt file, a break is indicated by an "X" on column 107 in the AWY1 lines:

L AN 0001 00107  AR11    AIRWAY GAP FLAG INDICATOR
                         'X' ENTERED WHEN AIRWAY DISCONTINUED

**Comment by Nikolai558** [comment]
Hello Chuck,
I have found something to note. Right now your Airways are "incomplete." Look at V328 for example. Your parser gives out 11 fixes, the correct number of fixes in this airway is 23.

In SCToutput.cs roughly line 477; "If (CurAwy == PrevAwy)" If you change this specific line to "If (CurAwy != PrevAwy)" it will give you all the missing fixes with some additional ones at the start and ending. 

This means in the same file, roughly line 500; "PrevAwy = CurAwy" is in the wrong place. I am currently looking at where it should be. I will keep you updated via discord or in here.

**Comment by drchuck59** [comment]
Airways breaks added with rewrite of airway selection method (to catch missing airways)
Oceanic and UltraHigh enroute are NOT in this program, so do not delete them from your SCT2 file.

**Comment by KSanders7070** [comment]
The line on V200 from FMG and BVL is still drawn so it must not be picking up this break (1.1.2)

**Comment by Nikolai558** [comment]
I'm not sure if this has to do with the breaks or not but this is happening as well. See below image. Also, I'm not sure what your program is doing to gather the  airway data points (fixes, VOR's) but here's what I think might be causing some issues. 

Does your program consider points outside of the "Selection Square Boundary?" Meaning, if airway point is in the "Selection Square Boundary" draw to that point, if its not what does your program do? It should draw it to that point but then only keep the airway line up to the "Selection Square Boundary" I honestly think that this is where the some of the issues are originating from. 


SUGGESTED LOGIC: 
```
If (NEXT_FIX is within SELECTION_SQUARE_BOUNDARY):
     Draw Airway line from PREVIOUS_FIX to NEXT_FIX
Else: 
      Draw Airway from PREVIOUS_FIX to POINT_AT_WHICH_IT_INTERSECTS_SELECTION_SQUARE_BOUNDARY. 

```

![image](https://user-images.githubusercontent.com/38259407/85250486-efdf7980-b413-11ea-9133-0a6c0bc7102d.png)

![image](https://user-images.githubusercontent.com/38259407/85251711-400c0b00-b417-11ea-89eb-33fe2f5818a8.png)
