### ISSUE TITLE
Eastern MAG VAR Needs Negative

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#8]
EXAMPLE:
ZLC_2006
ZLC_xx_OBS
SLC
N043.12.22.497
W111.19.59.995
60
50.4
11
1

should be:
ZLC_2006
ZLC_xx_OBS
SLC
N043.12.22.497
W111.19.59.995
60
50.4
-11
1

**Comment by KSanders7070** [comment]
Additional info:

From APT.txt file, the MAG VAR for KSLC airport is "11E"

If you could write in your code to query the letter after the number of degrees and if it is a "E", then have it make the MAG VAR value in the INFO section of the SCT be a negative number.

**Comment by KSanders7070** [comment]
user input of a - in the MAG VAR box on the GUI doesn't transfer to the output file.

**Comment by drchuck59** [comment]
Corrected (hopefully) in version 1.1.0  Please retest.

**Comment by KSanders7070** [comment]
This seems to have fixed however, there now seems to be some issues with the Runway Centerlines that I think that the Negative Mag is creating possibly. I will make a separate issue report for that.
