### ISSUE TITLE
Random/Erroneous Line & Text Drawing

### ISSUE THREAD

**Issue by KSanders7070** [drchuck59/SCTBuilder#9]
Example:

SLC LEEHY STAR

Line Draw image shows a red X on the lines that need to be deleted and lines through the "SLC (AA)" point that does not appear to be a fixed point and is not needed at all.
![Corrected Line Draw Output](https://user-images.githubusercontent.com/63331106/82519868-bd7aed80-9af0-11ea-8a60-6e1bb580d250.JPG)

The SLC text section needs to go away completely as it is not needed and it is drawing over the PLAGE waypoint.
![Random SLC Text](https://user-images.githubusercontent.com/63331106/82519869-be138400-9af0-11ea-870c-809365b282eb.JPG)

**Comment by drchuck59** [comment]
Both issues are corrected in version 1.1.0.  (The user can elect to not draw the letters or simply delete them from the file.)

**Comment by KSanders7070** [comment]
1) Seems to be mostly fixed but take for example the LEEHY STAR into KSLC again... there is a line between EKR and SPANE that should not be there. The line above it going from EKR - MTU - SPANE is correct. Line "SPANE EKR" needs to be removed.
![Capture](https://user-images.githubusercontent.com/63331106/84969546-ed64e300-b0e6-11ea-9217-1facf732af83.JPG)
![Capture](https://user-images.githubusercontent.com/63331106/84971396-a11ba200-b0ea-11ea-83b0-aac434cde391.JPG)

2) I selected in preferences to Draw the FIXes on Diagram but there is no indication that it "took" the selection and it didn't actually write them to the diagram.
